stages:
  - pre-commit
  - deploy

before_script:
  - apt-get update
  - apt-get install redis-server -y
  - redis-server --daemonize yes
  - python -V
  - pip install tox

pre-commit-check:
  stage: pre-commit
  image: python:3.6-buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

deploy-pypi:
  stage: deploy
  image: python:3.7-buster
  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags
